### ISSUE TITLE
Random selection still tries to select deleted items

### ISSUE THREAD

**Issue by ben-ward1** [BenjaminEllisWard/RQG#1]
When calling QuestionsController.Random(), the rnd.Next() statement can still select id numbers that have been deleted from the database.

This behavior is reproduced by running the project, deleting items from the Question Bank page, and then generating random questions until an exception occurs.

**Comment by maxalmonte14** [comment]
I solved this problem on my own repo, I even added a test to verify the method behaves as expected.

I would love to make a PR to add it to the main repo, but before that, you have to accept my first PR, because I'm using the new project structure with the RQG namespace 😅

Anyway you can check my implementation in here 👍

https://github.com/maxalmonte14/RQG/tree/hotfix/solved_NullReferenceException_problem_when_generating_random_questions
